// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xencryptdecrypt.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XEncryptdecrypt_CfgInitialize(XEncryptdecrypt *InstancePtr, XEncryptdecrypt_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->S_axi_bundle_BaseAddress = ConfigPtr->S_axi_bundle_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XEncryptdecrypt_Start(XEncryptdecrypt *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEncryptdecrypt_ReadReg(InstancePtr->S_axi_bundle_BaseAddress, XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_AP_CTRL) & 0x80;
    XEncryptdecrypt_WriteReg(InstancePtr->S_axi_bundle_BaseAddress, XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_AP_CTRL, Data | 0x01);
}

u32 XEncryptdecrypt_IsDone(XEncryptdecrypt *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEncryptdecrypt_ReadReg(InstancePtr->S_axi_bundle_BaseAddress, XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XEncryptdecrypt_IsIdle(XEncryptdecrypt *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEncryptdecrypt_ReadReg(InstancePtr->S_axi_bundle_BaseAddress, XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XEncryptdecrypt_IsReady(XEncryptdecrypt *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XEncryptdecrypt_ReadReg(InstancePtr->S_axi_bundle_BaseAddress, XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XEncryptdecrypt_EnableAutoRestart(XEncryptdecrypt *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEncryptdecrypt_WriteReg(InstancePtr->S_axi_bundle_BaseAddress, XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_AP_CTRL, 0x80);
}

void XEncryptdecrypt_DisableAutoRestart(XEncryptdecrypt *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEncryptdecrypt_WriteReg(InstancePtr->S_axi_bundle_BaseAddress, XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_AP_CTRL, 0);
}

u32 XEncryptdecrypt_Get_a_BaseAddress(XEncryptdecrypt *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->S_axi_bundle_BaseAddress + XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_A_BASE);
}

u32 XEncryptdecrypt_Get_a_HighAddress(XEncryptdecrypt *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->S_axi_bundle_BaseAddress + XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_A_HIGH);
}

u32 XEncryptdecrypt_Get_a_TotalBytes(XEncryptdecrypt *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_A_HIGH - XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_A_BASE + 1);
}

u32 XEncryptdecrypt_Get_a_BitWidth(XEncryptdecrypt *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XENCRYPTDECRYPT_S_AXI_BUNDLE_WIDTH_A;
}

u32 XEncryptdecrypt_Get_a_Depth(XEncryptdecrypt *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XENCRYPTDECRYPT_S_AXI_BUNDLE_DEPTH_A;
}

u32 XEncryptdecrypt_Write_a_Words(XEncryptdecrypt *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_A_HIGH - XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_A_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->S_axi_bundle_BaseAddress + XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_A_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XEncryptdecrypt_Read_a_Words(XEncryptdecrypt *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_A_HIGH - XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_A_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->S_axi_bundle_BaseAddress + XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_A_BASE + (offset + i)*4);
    }
    return length;
}

u32 XEncryptdecrypt_Write_a_Bytes(XEncryptdecrypt *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_A_HIGH - XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_A_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->S_axi_bundle_BaseAddress + XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_A_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XEncryptdecrypt_Read_a_Bytes(XEncryptdecrypt *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_A_HIGH - XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_A_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->S_axi_bundle_BaseAddress + XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_A_BASE + offset + i);
    }
    return length;
}

u32 XEncryptdecrypt_Get_c1_BaseAddress(XEncryptdecrypt *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->S_axi_bundle_BaseAddress + XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_C1_BASE);
}

u32 XEncryptdecrypt_Get_c1_HighAddress(XEncryptdecrypt *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->S_axi_bundle_BaseAddress + XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_C1_HIGH);
}

u32 XEncryptdecrypt_Get_c1_TotalBytes(XEncryptdecrypt *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_C1_HIGH - XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_C1_BASE + 1);
}

u32 XEncryptdecrypt_Get_c1_BitWidth(XEncryptdecrypt *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XENCRYPTDECRYPT_S_AXI_BUNDLE_WIDTH_C1;
}

u32 XEncryptdecrypt_Get_c1_Depth(XEncryptdecrypt *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XENCRYPTDECRYPT_S_AXI_BUNDLE_DEPTH_C1;
}

u32 XEncryptdecrypt_Write_c1_Words(XEncryptdecrypt *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_C1_HIGH - XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_C1_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->S_axi_bundle_BaseAddress + XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_C1_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XEncryptdecrypt_Read_c1_Words(XEncryptdecrypt *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_C1_HIGH - XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_C1_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->S_axi_bundle_BaseAddress + XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_C1_BASE + (offset + i)*4);
    }
    return length;
}

u32 XEncryptdecrypt_Write_c1_Bytes(XEncryptdecrypt *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_C1_HIGH - XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_C1_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->S_axi_bundle_BaseAddress + XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_C1_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XEncryptdecrypt_Read_c1_Bytes(XEncryptdecrypt *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_C1_HIGH - XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_C1_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->S_axi_bundle_BaseAddress + XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_C1_BASE + offset + i);
    }
    return length;
}

u32 XEncryptdecrypt_Get_c2_BaseAddress(XEncryptdecrypt *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->S_axi_bundle_BaseAddress + XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_C2_BASE);
}

u32 XEncryptdecrypt_Get_c2_HighAddress(XEncryptdecrypt *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->S_axi_bundle_BaseAddress + XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_C2_HIGH);
}

u32 XEncryptdecrypt_Get_c2_TotalBytes(XEncryptdecrypt *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_C2_HIGH - XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_C2_BASE + 1);
}

u32 XEncryptdecrypt_Get_c2_BitWidth(XEncryptdecrypt *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XENCRYPTDECRYPT_S_AXI_BUNDLE_WIDTH_C2;
}

u32 XEncryptdecrypt_Get_c2_Depth(XEncryptdecrypt *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XENCRYPTDECRYPT_S_AXI_BUNDLE_DEPTH_C2;
}

u32 XEncryptdecrypt_Write_c2_Words(XEncryptdecrypt *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_C2_HIGH - XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_C2_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->S_axi_bundle_BaseAddress + XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_C2_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XEncryptdecrypt_Read_c2_Words(XEncryptdecrypt *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_C2_HIGH - XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_C2_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->S_axi_bundle_BaseAddress + XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_C2_BASE + (offset + i)*4);
    }
    return length;
}

u32 XEncryptdecrypt_Write_c2_Bytes(XEncryptdecrypt *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_C2_HIGH - XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_C2_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->S_axi_bundle_BaseAddress + XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_C2_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XEncryptdecrypt_Read_c2_Bytes(XEncryptdecrypt *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_C2_HIGH - XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_C2_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->S_axi_bundle_BaseAddress + XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_C2_BASE + offset + i);
    }
    return length;
}

u32 XEncryptdecrypt_Get_m_BaseAddress(XEncryptdecrypt *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->S_axi_bundle_BaseAddress + XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_M_BASE);
}

u32 XEncryptdecrypt_Get_m_HighAddress(XEncryptdecrypt *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->S_axi_bundle_BaseAddress + XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_M_HIGH);
}

u32 XEncryptdecrypt_Get_m_TotalBytes(XEncryptdecrypt *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_M_HIGH - XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_M_BASE + 1);
}

u32 XEncryptdecrypt_Get_m_BitWidth(XEncryptdecrypt *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XENCRYPTDECRYPT_S_AXI_BUNDLE_WIDTH_M;
}

u32 XEncryptdecrypt_Get_m_Depth(XEncryptdecrypt *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XENCRYPTDECRYPT_S_AXI_BUNDLE_DEPTH_M;
}

u32 XEncryptdecrypt_Write_m_Words(XEncryptdecrypt *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_M_HIGH - XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_M_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->S_axi_bundle_BaseAddress + XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_M_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XEncryptdecrypt_Read_m_Words(XEncryptdecrypt *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_M_HIGH - XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_M_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->S_axi_bundle_BaseAddress + XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_M_BASE + (offset + i)*4);
    }
    return length;
}

u32 XEncryptdecrypt_Write_m_Bytes(XEncryptdecrypt *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_M_HIGH - XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_M_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->S_axi_bundle_BaseAddress + XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_M_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XEncryptdecrypt_Read_m_Bytes(XEncryptdecrypt *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_M_HIGH - XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_M_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->S_axi_bundle_BaseAddress + XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_M_BASE + offset + i);
    }
    return length;
}

u32 XEncryptdecrypt_Get_p_BaseAddress(XEncryptdecrypt *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->S_axi_bundle_BaseAddress + XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_P_BASE);
}

u32 XEncryptdecrypt_Get_p_HighAddress(XEncryptdecrypt *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->S_axi_bundle_BaseAddress + XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_P_HIGH);
}

u32 XEncryptdecrypt_Get_p_TotalBytes(XEncryptdecrypt *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_P_HIGH - XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_P_BASE + 1);
}

u32 XEncryptdecrypt_Get_p_BitWidth(XEncryptdecrypt *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XENCRYPTDECRYPT_S_AXI_BUNDLE_WIDTH_P;
}

u32 XEncryptdecrypt_Get_p_Depth(XEncryptdecrypt *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XENCRYPTDECRYPT_S_AXI_BUNDLE_DEPTH_P;
}

u32 XEncryptdecrypt_Write_p_Words(XEncryptdecrypt *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_P_HIGH - XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_P_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->S_axi_bundle_BaseAddress + XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_P_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XEncryptdecrypt_Read_p_Words(XEncryptdecrypt *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_P_HIGH - XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_P_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->S_axi_bundle_BaseAddress + XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_P_BASE + (offset + i)*4);
    }
    return length;
}

u32 XEncryptdecrypt_Write_p_Bytes(XEncryptdecrypt *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_P_HIGH - XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_P_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->S_axi_bundle_BaseAddress + XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_P_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XEncryptdecrypt_Read_p_Bytes(XEncryptdecrypt *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_P_HIGH - XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_P_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->S_axi_bundle_BaseAddress + XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_P_BASE + offset + i);
    }
    return length;
}

u32 XEncryptdecrypt_Get_r2_BaseAddress(XEncryptdecrypt *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->S_axi_bundle_BaseAddress + XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_R2_BASE);
}

u32 XEncryptdecrypt_Get_r2_HighAddress(XEncryptdecrypt *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (InstancePtr->S_axi_bundle_BaseAddress + XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_R2_HIGH);
}

u32 XEncryptdecrypt_Get_r2_TotalBytes(XEncryptdecrypt *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return (XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_R2_HIGH - XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_R2_BASE + 1);
}

u32 XEncryptdecrypt_Get_r2_BitWidth(XEncryptdecrypt *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XENCRYPTDECRYPT_S_AXI_BUNDLE_WIDTH_R2;
}

u32 XEncryptdecrypt_Get_r2_Depth(XEncryptdecrypt *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XENCRYPTDECRYPT_S_AXI_BUNDLE_DEPTH_R2;
}

u32 XEncryptdecrypt_Write_r2_Words(XEncryptdecrypt *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_R2_HIGH - XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_R2_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(int *)(InstancePtr->S_axi_bundle_BaseAddress + XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_R2_BASE + (offset + i)*4) = *(data + i);
    }
    return length;
}

u32 XEncryptdecrypt_Read_r2_Words(XEncryptdecrypt *InstancePtr, int offset, int *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length)*4 > (XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_R2_HIGH - XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_R2_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(int *)(InstancePtr->S_axi_bundle_BaseAddress + XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_R2_BASE + (offset + i)*4);
    }
    return length;
}

u32 XEncryptdecrypt_Write_r2_Bytes(XEncryptdecrypt *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_R2_HIGH - XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_R2_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(char *)(InstancePtr->S_axi_bundle_BaseAddress + XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_R2_BASE + offset + i) = *(data + i);
    }
    return length;
}

u32 XEncryptdecrypt_Read_r2_Bytes(XEncryptdecrypt *InstancePtr, int offset, char *data, int length) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr -> IsReady == XIL_COMPONENT_IS_READY);

    int i;

    if ((offset + length) > (XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_R2_HIGH - XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_R2_BASE + 1))
        return 0;

    for (i = 0; i < length; i++) {
        *(data + i) = *(char *)(InstancePtr->S_axi_bundle_BaseAddress + XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_R2_BASE + offset + i);
    }
    return length;
}

void XEncryptdecrypt_InterruptGlobalEnable(XEncryptdecrypt *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEncryptdecrypt_WriteReg(InstancePtr->S_axi_bundle_BaseAddress, XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_GIE, 1);
}

void XEncryptdecrypt_InterruptGlobalDisable(XEncryptdecrypt *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEncryptdecrypt_WriteReg(InstancePtr->S_axi_bundle_BaseAddress, XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_GIE, 0);
}

void XEncryptdecrypt_InterruptEnable(XEncryptdecrypt *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XEncryptdecrypt_ReadReg(InstancePtr->S_axi_bundle_BaseAddress, XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_IER);
    XEncryptdecrypt_WriteReg(InstancePtr->S_axi_bundle_BaseAddress, XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_IER, Register | Mask);
}

void XEncryptdecrypt_InterruptDisable(XEncryptdecrypt *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XEncryptdecrypt_ReadReg(InstancePtr->S_axi_bundle_BaseAddress, XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_IER);
    XEncryptdecrypt_WriteReg(InstancePtr->S_axi_bundle_BaseAddress, XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_IER, Register & (~Mask));
}

void XEncryptdecrypt_InterruptClear(XEncryptdecrypt *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XEncryptdecrypt_WriteReg(InstancePtr->S_axi_bundle_BaseAddress, XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_ISR, Mask);
}

u32 XEncryptdecrypt_InterruptGetEnabled(XEncryptdecrypt *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XEncryptdecrypt_ReadReg(InstancePtr->S_axi_bundle_BaseAddress, XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_IER);
}

u32 XEncryptdecrypt_InterruptGetStatus(XEncryptdecrypt *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XEncryptdecrypt_ReadReg(InstancePtr->S_axi_bundle_BaseAddress, XENCRYPTDECRYPT_S_AXI_BUNDLE_ADDR_ISR);
}

