// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2017.4
// Copyright (C) 1986-2017 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module inv_ntt2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        a_address0,
        a_ce0,
        a_we0,
        a_d0,
        a_q0
);

parameter    ap_ST_fsm_state1 = 35'd1;
parameter    ap_ST_fsm_state2 = 35'd2;
parameter    ap_ST_fsm_state3 = 35'd4;
parameter    ap_ST_fsm_state4 = 35'd8;
parameter    ap_ST_fsm_state5 = 35'd16;
parameter    ap_ST_fsm_state6 = 35'd32;
parameter    ap_ST_fsm_state7 = 35'd64;
parameter    ap_ST_fsm_state8 = 35'd128;
parameter    ap_ST_fsm_state9 = 35'd256;
parameter    ap_ST_fsm_state10 = 35'd512;
parameter    ap_ST_fsm_state11 = 35'd1024;
parameter    ap_ST_fsm_state12 = 35'd2048;
parameter    ap_ST_fsm_state13 = 35'd4096;
parameter    ap_ST_fsm_state14 = 35'd8192;
parameter    ap_ST_fsm_state15 = 35'd16384;
parameter    ap_ST_fsm_state16 = 35'd32768;
parameter    ap_ST_fsm_state17 = 35'd65536;
parameter    ap_ST_fsm_state18 = 35'd131072;
parameter    ap_ST_fsm_state19 = 35'd262144;
parameter    ap_ST_fsm_state20 = 35'd524288;
parameter    ap_ST_fsm_state21 = 35'd1048576;
parameter    ap_ST_fsm_state22 = 35'd2097152;
parameter    ap_ST_fsm_state23 = 35'd4194304;
parameter    ap_ST_fsm_state24 = 35'd8388608;
parameter    ap_ST_fsm_state25 = 35'd16777216;
parameter    ap_ST_fsm_pp1_stage0 = 35'd33554432;
parameter    ap_ST_fsm_pp1_stage1 = 35'd67108864;
parameter    ap_ST_fsm_pp1_stage2 = 35'd134217728;
parameter    ap_ST_fsm_pp1_stage3 = 35'd268435456;
parameter    ap_ST_fsm_state42 = 35'd536870912;
parameter    ap_ST_fsm_pp2_stage0 = 35'd1073741824;
parameter    ap_ST_fsm_pp2_stage1 = 35'd2147483648;
parameter    ap_ST_fsm_pp2_stage2 = 35'd4294967296;
parameter    ap_ST_fsm_pp2_stage3 = 35'd8589934592;
parameter    ap_ST_fsm_state59 = 35'd17179869184;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] a_address0;
output   a_ce0;
output   a_we0;
output  [15:0] a_d0;
input  [15:0] a_q0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[7:0] a_address0;
reg a_ce0;
reg a_we0;
reg[15:0] a_d0;

(* fsm_encoding = "none" *) reg   [34:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [14:0] omega_1_reg_227;
reg   [8:0] j_1_reg_238;
reg   [14:0] omega_2_reg_250;
reg   [8:0] j_2_reg_261;
reg   [14:0] omega2_reg_273;
reg   [15:0] reg_294;
wire    ap_CS_fsm_state7;
wire    ap_CS_fsm_pp1_stage2;
reg    ap_enable_reg_pp1_iter1;
wire    ap_block_state28_pp1_stage2_iter0;
wire    ap_block_state32_pp1_stage2_iter1;
wire    ap_block_state36_pp1_stage2_iter2;
wire    ap_block_state40_pp1_stage2_iter3;
wire    ap_block_pp1_stage2_11001;
reg   [0:0] tmp_106_reg_1086;
reg   [0:0] ap_reg_pp1_iter1_tmp_106_reg_1086;
wire   [14:0] grp_mod_r_fu_284_ap_return;
reg   [14:0] reg_298;
wire    ap_CS_fsm_state10;
wire    ap_CS_fsm_state11;
wire    ap_CS_fsm_state15;
wire    ap_CS_fsm_state16;
wire    ap_CS_fsm_state17;
wire    ap_CS_fsm_state18;
wire    ap_CS_fsm_pp1_stage0;
wire    ap_block_state26_pp1_stage0_iter0;
wire    ap_block_state30_pp1_stage0_iter1;
wire    ap_block_state34_pp1_stage0_iter2;
wire    ap_block_state38_pp1_stage0_iter3;
wire    ap_block_pp1_stage0_11001;
wire    ap_CS_fsm_pp2_stage0;
reg    ap_enable_reg_pp2_iter1;
wire    ap_block_state43_pp2_stage0_iter0;
wire    ap_block_state47_pp2_stage0_iter1;
wire    ap_block_state51_pp2_stage0_iter2;
wire    ap_block_state55_pp2_stage0_iter3;
wire    ap_block_pp2_stage0_11001;
reg   [0:0] tmp_110_reg_1145;
reg   [14:0] reg_304;
wire    ap_CS_fsm_state25;
wire    ap_CS_fsm_pp1_stage3;
reg    ap_enable_reg_pp1_iter2;
wire    ap_block_state29_pp1_stage3_iter0;
wire    ap_block_state33_pp1_stage3_iter1;
wire    ap_block_state37_pp1_stage3_iter2;
wire    ap_block_state41_pp1_stage3_iter3;
wire    ap_block_pp1_stage3_11001;
reg   [0:0] ap_reg_pp1_iter2_tmp_106_reg_1086;
wire    ap_CS_fsm_pp2_stage2;
wire    ap_block_state45_pp2_stage2_iter0;
wire    ap_block_state49_pp2_stage2_iter1;
wire    ap_block_state53_pp2_stage2_iter2;
wire    ap_block_state57_pp2_stage2_iter3;
wire    ap_block_pp2_stage2_11001;
reg   [0:0] ap_reg_pp2_iter1_tmp_110_reg_1145;
wire    ap_CS_fsm_pp2_stage3;
wire    ap_block_state46_pp2_stage3_iter0;
wire    ap_block_state50_pp2_stage3_iter1;
wire    ap_block_state54_pp2_stage3_iter2;
wire    ap_block_state58_pp2_stage3_iter3;
wire    ap_block_pp2_stage3_11001;
wire    ap_CS_fsm_pp2_stage1;
reg    ap_enable_reg_pp2_iter3;
wire    ap_block_state44_pp2_stage1_iter0;
wire    ap_block_state48_pp2_stage1_iter1;
wire    ap_block_state52_pp2_stage1_iter2;
wire    ap_block_state56_pp2_stage1_iter3;
wire    ap_block_pp2_stage1_11001;
reg   [0:0] ap_reg_pp2_iter3_tmp_110_reg_1145;
wire   [0:0] tmp_fu_309_p2;
wire    ap_CS_fsm_state2;
wire  signed [31:0] primrt_1_fu_423_p3;
reg  signed [31:0] primrt_1_reg_966;
wire   [31:0] tmp_45_fu_479_p3;
reg   [31:0] tmp_45_reg_972;
wire   [30:0] tmp_105_fu_487_p1;
reg   [30:0] tmp_105_reg_977;
wire   [0:0] tmp_46_fu_499_p2;
wire    ap_CS_fsm_state3;
wire   [30:0] j_6_fu_504_p2;
reg   [30:0] j_6_reg_986;
wire   [31:0] omega4_cast_fu_510_p1;
reg   [31:0] omega4_cast_reg_991;
wire   [31:0] m_1_fu_514_p2;
reg   [7:0] a_addr_8_reg_1006;
wire    ap_CS_fsm_state4;
wire   [0:0] icmp_fu_530_p2;
reg   [7:0] a_addr_9_reg_1011;
reg   [7:0] a_addr_10_reg_1016;
reg   [7:0] a_addr_11_reg_1021;
wire   [31:0] k_1_fu_599_p2;
reg   [31:0] k_1_reg_1026;
wire   [31:0] t1_1_fu_901_p2;
reg   [31:0] t1_1_reg_1031;
wire    ap_CS_fsm_state5;
wire   [31:0] t2_fu_906_p2;
reg   [31:0] t2_reg_1036;
wire    ap_CS_fsm_state6;
reg   [15:0] a_load_8_reg_1041;
wire    ap_CS_fsm_state8;
wire   [31:0] tmp_116_cast_fu_631_p1;
wire   [16:0] tmp_75_fu_636_p2;
reg   [16:0] tmp_75_reg_1051;
wire   [31:0] tmp_120_cast_fu_659_p1;
wire    ap_CS_fsm_state12;
wire   [16:0] tmp_79_fu_664_p2;
reg   [16:0] tmp_79_reg_1061;
wire  signed [31:0] tmp_118_cast_fu_670_p1;
wire    ap_CS_fsm_state13;
wire  signed [31:0] tmp_122_cast_fu_674_p1;
wire    ap_CS_fsm_state14;
wire   [31:0] omega_3_fu_698_p2;
reg   [31:0] omega_3_reg_1076;
wire    ap_CS_fsm_state20;
wire  signed [15:0] omega_1_cast3_fu_702_p1;
reg  signed [15:0] omega_1_cast3_reg_1081;
wire   [0:0] tmp_106_fu_706_p3;
reg   [0:0] ap_reg_pp1_iter3_tmp_106_reg_1086;
reg   [7:0] a_addr_reg_1090;
reg   [7:0] ap_reg_pp1_iter1_a_addr_reg_1090;
reg   [7:0] ap_reg_pp1_iter2_a_addr_reg_1090;
reg   [7:0] ap_reg_pp1_iter3_a_addr_reg_1090;
reg   [7:0] a_addr_5_reg_1095;
reg   [7:0] ap_reg_pp1_iter1_a_addr_5_reg_1095;
reg   [7:0] ap_reg_pp1_iter2_a_addr_5_reg_1095;
reg   [7:0] ap_reg_pp1_iter3_a_addr_5_reg_1095;
wire   [31:0] omega_cast_fu_738_p1;
wire   [31:0] t1_fu_918_p2;
reg   [31:0] t1_reg_1105;
wire    ap_CS_fsm_pp1_stage1;
wire    ap_block_state27_pp1_stage1_iter0;
wire    ap_block_state31_pp1_stage1_iter1;
wire    ap_block_state35_pp1_stage1_iter2;
wire    ap_block_state39_pp1_stage1_iter3;
wire    ap_block_pp1_stage1_11001;
wire   [8:0] j_3_fu_749_p2;
reg   [8:0] j_3_reg_1110;
reg    ap_enable_reg_pp1_iter0;
wire   [31:0] tmp_76_cast_fu_773_p1;
wire   [16:0] tmp_54_fu_778_p2;
reg   [16:0] tmp_54_reg_1120;
wire  signed [31:0] tmp_78_cast_fu_784_p1;
reg   [14:0] tmp_55_reg_1130;
reg    ap_enable_reg_pp1_iter3;
wire  signed [15:0] omega_2_cast2_fu_797_p1;
reg  signed [15:0] omega_2_cast2_reg_1135;
wire  signed [15:0] omega2_cast1_fu_801_p1;
reg  signed [15:0] omega2_cast1_reg_1140;
wire   [0:0] tmp_110_fu_805_p3;
reg   [0:0] ap_reg_pp2_iter2_tmp_110_reg_1145;
wire   [7:0] tmp_112_fu_817_p1;
reg   [7:0] tmp_112_reg_1149;
reg   [7:0] a_addr_6_reg_1154;
reg   [7:0] ap_reg_pp2_iter1_a_addr_6_reg_1154;
reg   [7:0] ap_reg_pp2_iter2_a_addr_6_reg_1154;
reg   [7:0] ap_reg_pp2_iter3_a_addr_6_reg_1154;
wire   [31:0] omega_4_cast_fu_830_p1;
wire   [31:0] omega2_1_cast_fu_834_p1;
wire   [31:0] tmp_84_fu_938_p2;
reg   [31:0] tmp_84_reg_1169;
reg   [7:0] a_addr_7_reg_1174;
reg   [7:0] ap_reg_pp2_iter1_a_addr_7_reg_1174;
reg   [7:0] ap_reg_pp2_iter2_a_addr_7_reg_1174;
reg   [7:0] ap_reg_pp2_iter3_a_addr_7_reg_1174;
wire   [31:0] tmp_90_fu_944_p2;
reg   [31:0] tmp_90_reg_1179;
wire   [8:0] j_5_fu_862_p2;
reg   [8:0] j_5_reg_1184;
reg    ap_enable_reg_pp2_iter0;
wire   [14:0] grp_mod_r_fu_289_ap_return;
wire   [29:0] tmp_86_fu_950_p2;
reg   [29:0] tmp_86_reg_1194;
wire   [31:0] tmp_88_cast_fu_876_p1;
wire   [29:0] tmp_92_fu_956_p2;
reg   [29:0] tmp_92_reg_1204;
wire   [31:0] tmp_95_cast_fu_888_p1;
reg   [14:0] tmp_93_reg_1214;
wire    ap_block_pp1_stage0_subdone;
reg    ap_condition_pp1_exit_iter0_state26;
wire    ap_block_pp1_stage3_subdone;
wire    ap_CS_fsm_state42;
wire    ap_block_pp2_stage0_subdone;
reg    ap_condition_pp2_exit_iter0_state43;
wire    ap_block_pp2_stage3_subdone;
reg    ap_enable_reg_pp2_iter2;
reg   [31:0] grp_mod_r_fu_284_x;
reg    grp_mod_r_fu_284_ap_ce;
wire    ap_CS_fsm_state21;
wire    ap_CS_fsm_state19;
wire    ap_CS_fsm_state59;
reg   [31:0] grp_mod_r_fu_289_x;
reg    grp_mod_r_fu_289_ap_ce;
reg   [31:0] primrt_reg_170;
reg   [31:0] m_reg_181;
reg   [14:0] omega4_reg_193;
reg   [30:0] j4_reg_204;
reg   [31:0] k_reg_216;
reg   [14:0] ap_phi_mux_omega_1_phi_fu_231_p4;
wire    ap_block_pp1_stage0;
reg   [8:0] ap_phi_mux_j_1_phi_fu_242_p4;
reg   [14:0] ap_phi_mux_omega_2_phi_fu_254_p4;
wire    ap_block_pp2_stage0;
reg   [8:0] ap_phi_mux_j_2_phi_fu_265_p4;
reg   [14:0] ap_phi_mux_omega2_phi_fu_277_p4;
wire    ap_block_pp1_stage2;
wire    ap_block_pp1_stage3;
wire    ap_block_pp1_stage1;
wire    ap_block_pp2_stage2;
wire    ap_block_pp2_stage3;
wire    ap_block_pp2_stage1;
wire  signed [63:0] tmp_62_fu_560_p1;
wire  signed [63:0] tmp_65_fu_565_p1;
wire  signed [63:0] tmp_69_fu_589_p1;
wire  signed [63:0] tmp_72_fu_594_p1;
wire   [63:0] tmp_48_fu_722_p1;
wire   [63:0] tmp_49_fu_733_p1;
wire   [63:0] tmp_82_fu_825_p1;
wire   [63:0] tmp_88_fu_850_p1;
wire  signed [15:0] p_trunc_ext_fu_678_p1;
wire  signed [15:0] p_trunc22_ext_fu_683_p1;
wire  signed [15:0] p_trunc21_ext_fu_688_p1;
wire  signed [15:0] p_trunc23_ext_fu_693_p1;
wire  signed [15:0] p_trunc24_ext_fu_788_p1;
wire  signed [15:0] p_trunc25_ext_fu_793_p1;
wire  signed [15:0] p_trunc26_ext_fu_892_p1;
wire  signed [15:0] p_trunc27_ext_fu_897_p1;
wire   [0:0] sel_tmp_fu_315_p2;
wire   [0:0] sel_tmp4_fu_335_p2;
wire   [0:0] sel_tmp2_fu_329_p2;
wire   [0:0] tmp_27_fu_349_p2;
wire   [31:0] sel_tmp3_cast_fu_341_p3;
wire   [31:0] sel_tmp1_fu_321_p3;
wire   [0:0] sel_tmp8_fu_369_p2;
wire   [0:0] sel_tmp6_fu_363_p2;
wire   [0:0] tmp_28_fu_383_p2;
wire   [31:0] sel_tmp7_cast_fu_375_p3;
wire   [31:0] sel_tmp5_fu_355_p3;
wire   [0:0] sel_tmp7_fu_403_p2;
wire   [0:0] sel_tmp3_fu_397_p2;
wire   [0:0] tmp_29_fu_417_p2;
wire   [31:0] sel_tmp11_cast_fu_409_p3;
wire   [31:0] sel_tmp9_fu_389_p3;
wire   [31:0] p_neg_fu_439_p2;
wire   [30:0] p_lshr_fu_445_p4;
wire   [31:0] tmp_41_fu_455_p1;
wire   [30:0] p_lshr_f_fu_465_p4;
wire   [0:0] tmp_104_fu_431_p3;
wire   [31:0] p_neg_t_fu_459_p2;
wire   [31:0] tmp_42_fu_475_p1;
wire   [31:0] j4_cast_fu_495_p1;
wire  signed [15:0] omega4_cast4_fu_491_p1;
wire   [24:0] tmp_109_fu_520_p4;
wire   [30:0] tmp_111_fu_536_p1;
wire   [30:0] tmp_58_fu_540_p2;
wire   [31:0] tmp_59_fu_546_p3;
wire   [31:0] tmp_60_fu_554_p2;
wire   [30:0] tmp_66_fu_570_p2;
wire   [31:0] tmp_67_fu_575_p3;
wire   [31:0] tmp_68_fu_583_p2;
wire  signed [15:0] t1_3_trunc_ext_fu_613_p1;
wire   [16:0] u1_1_cast_fu_621_p1;
wire   [16:0] t1_3_cast_fu_617_p1;
wire   [16:0] tmp_73_fu_625_p2;
wire  signed [15:0] t2_1_trunc_ext_fu_642_p1;
wire   [16:0] u2_cast_fu_650_p1;
wire   [16:0] t2_1_cast_fu_646_p1;
wire   [16:0] tmp_77_fu_653_p2;
wire   [15:0] omega_3_fu_698_p1;
wire   [7:0] tmp_108_fu_718_p1;
wire   [7:0] j_fu_727_p2;
wire   [28:0] omega_fu_911_p2;
wire  signed [15:0] t1_1_trunc_ext_fu_759_p1;
wire   [16:0] t1_1_cast_fu_763_p1;
wire   [16:0] u1_cast_fu_755_p1;
wire   [16:0] tmp_52_fu_767_p2;
wire   [28:0] omega_4_fu_924_p2;
wire   [28:0] omega2_1_fu_931_p2;
wire   [7:0] j_4_fu_845_p2;
wire  signed [15:0] tmp_87_trunc_ext_fu_868_p1;
wire  signed [15:0] tmp_94_trunc_ext_fu_880_p1;
wire   [15:0] t1_1_fu_901_p0;
wire   [15:0] t1_1_fu_901_p1;
wire   [15:0] t2_fu_906_p0;
wire   [15:0] t2_fu_906_p1;
wire   [12:0] omega_fu_911_p0;
wire   [15:0] omega_fu_911_p1;
wire   [15:0] t1_fu_918_p0;
wire   [15:0] t1_fu_918_p1;
wire   [12:0] omega_4_fu_924_p0;
wire   [15:0] omega_4_fu_924_p1;
wire   [12:0] omega2_1_fu_931_p0;
wire   [15:0] omega2_1_fu_931_p1;
wire   [15:0] tmp_84_fu_938_p0;
wire   [15:0] tmp_84_fu_938_p1;
wire   [15:0] tmp_90_fu_944_p0;
wire   [15:0] tmp_90_fu_944_p1;
wire   [13:0] tmp_86_fu_950_p0;
wire   [15:0] tmp_86_fu_950_p1;
wire   [13:0] tmp_92_fu_956_p0;
wire   [15:0] tmp_92_fu_956_p1;
reg   [34:0] ap_NS_fsm;
wire    ap_block_pp1_stage1_subdone;
wire    ap_block_pp1_stage2_subdone;
wire    ap_block_pp2_stage1_subdone;
wire    ap_block_pp2_stage2_subdone;
reg    ap_idle_pp1;
wire    ap_enable_pp1;
reg    ap_idle_pp2;
wire    ap_enable_pp2;
wire   [28:0] omega2_1_fu_931_p10;
wire   [28:0] omega_4_fu_924_p10;
wire   [28:0] omega_fu_911_p10;
wire   [31:0] t1_1_fu_901_p10;
wire   [31:0] t1_fu_918_p00;
wire   [31:0] t1_fu_918_p10;
wire   [31:0] t2_fu_906_p10;
wire   [31:0] tmp_84_fu_938_p00;
wire   [31:0] tmp_84_fu_938_p10;
wire   [29:0] tmp_86_fu_950_p10;
wire   [31:0] tmp_90_fu_944_p00;
wire   [31:0] tmp_90_fu_944_p10;
wire   [29:0] tmp_92_fu_956_p10;

// power-on initialization
initial begin
#0 ap_CS_fsm = 35'd1;
#0 ap_enable_reg_pp1_iter1 = 1'b0;
#0 ap_enable_reg_pp2_iter1 = 1'b0;
#0 ap_enable_reg_pp1_iter2 = 1'b0;
#0 ap_enable_reg_pp2_iter3 = 1'b0;
#0 ap_enable_reg_pp1_iter0 = 1'b0;
#0 ap_enable_reg_pp1_iter3 = 1'b0;
#0 ap_enable_reg_pp2_iter0 = 1'b0;
#0 ap_enable_reg_pp2_iter2 = 1'b0;
end

mod_r grp_mod_r_fu_284(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .x(grp_mod_r_fu_284_x),
    .ap_return(grp_mod_r_fu_284_ap_return),
    .ap_ce(grp_mod_r_fu_284_ap_ce)
);

mod_r grp_mod_r_fu_289(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .x(grp_mod_r_fu_289_x),
    .ap_return(grp_mod_r_fu_289_ap_return),
    .ap_ce(grp_mod_r_fu_289_ap_ce)
);

encdec_mul_mul_168jQ #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
encdec_mul_mul_168jQ_U88(
    .din0(t1_1_fu_901_p0),
    .din1(t1_1_fu_901_p1),
    .dout(t1_1_fu_901_p2)
);

encdec_mul_mul_168jQ #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
encdec_mul_mul_168jQ_U89(
    .din0(t2_fu_906_p0),
    .din1(t2_fu_906_p1),
    .dout(t2_fu_906_p2)
);

encdec_mul_mul_139j0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 13 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 29 ))
encdec_mul_mul_139j0_U90(
    .din0(omega_fu_911_p0),
    .din1(omega_fu_911_p1),
    .dout(omega_fu_911_p2)
);

encdec_mul_mul_168jQ #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
encdec_mul_mul_168jQ_U91(
    .din0(t1_fu_918_p0),
    .din1(t1_fu_918_p1),
    .dout(t1_fu_918_p2)
);

encdec_mul_mul_139j0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 13 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 29 ))
encdec_mul_mul_139j0_U92(
    .din0(omega_4_fu_924_p0),
    .din1(omega_4_fu_924_p1),
    .dout(omega_4_fu_924_p2)
);

encdec_mul_mul_139j0 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 13 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 29 ))
encdec_mul_mul_139j0_U93(
    .din0(omega2_1_fu_931_p0),
    .din1(omega2_1_fu_931_p1),
    .dout(omega2_1_fu_931_p2)
);

encdec_mul_mul_168jQ #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
encdec_mul_mul_168jQ_U94(
    .din0(tmp_84_fu_938_p0),
    .din1(tmp_84_fu_938_p1),
    .dout(tmp_84_fu_938_p2)
);

encdec_mul_mul_168jQ #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 32 ))
encdec_mul_mul_168jQ_U95(
    .din0(tmp_90_fu_944_p0),
    .din1(tmp_90_fu_944_p1),
    .dout(tmp_90_fu_944_p2)
);

encdec_mul_mul_14bak #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 30 ))
encdec_mul_mul_14bak_U96(
    .din0(tmp_86_fu_950_p0),
    .din1(tmp_86_fu_950_p1),
    .dout(tmp_86_fu_950_p2)
);

encdec_mul_mul_14bak #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 14 ),
    .din1_WIDTH( 16 ),
    .dout_WIDTH( 30 ))
encdec_mul_mul_14bak_U97(
    .din0(tmp_92_fu_956_p0),
    .din1(tmp_92_fu_956_p1),
    .dout(tmp_92_fu_956_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage0_subdone) & (1'b1 == ap_condition_pp1_exit_iter0_state26) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
            ap_enable_reg_pp1_iter0 <= 1'b0;
        end else if (((tmp_fu_309_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp1_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage3_subdone) & (1'b1 == ap_CS_fsm_pp1_stage3))) begin
            if ((1'b1 == ap_condition_pp1_exit_iter0_state26)) begin
                ap_enable_reg_pp1_iter1 <= (1'b1 ^ ap_condition_pp1_exit_iter0_state26);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp1_iter1 <= ap_enable_reg_pp1_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage3_subdone) & (1'b1 == ap_CS_fsm_pp1_stage3))) begin
            ap_enable_reg_pp1_iter2 <= ap_enable_reg_pp1_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp1_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp1_stage3_subdone) & (1'b1 == ap_CS_fsm_pp1_stage3))) begin
            ap_enable_reg_pp1_iter3 <= ap_enable_reg_pp1_iter2;
        end else if (((tmp_fu_309_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_enable_reg_pp1_iter3 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp2_stage0_subdone) & (1'b1 == ap_condition_pp2_exit_iter0_state43) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
            ap_enable_reg_pp2_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state42)) begin
            ap_enable_reg_pp2_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp2_stage3_subdone) & (1'b1 == ap_CS_fsm_pp2_stage3))) begin
            if ((1'b1 == ap_condition_pp2_exit_iter0_state43)) begin
                ap_enable_reg_pp2_iter1 <= (1'b1 ^ ap_condition_pp2_exit_iter0_state43);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp2_iter1 <= ap_enable_reg_pp2_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp2_stage3_subdone) & (1'b1 == ap_CS_fsm_pp2_stage3))) begin
            ap_enable_reg_pp2_iter2 <= ap_enable_reg_pp2_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp2_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp2_stage3_subdone) & (1'b1 == ap_CS_fsm_pp2_stage3))) begin
            ap_enable_reg_pp2_iter3 <= ap_enable_reg_pp2_iter2;
        end else if ((1'b1 == ap_CS_fsm_state42)) begin
            ap_enable_reg_pp2_iter3 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        j4_reg_204 <= j_6_reg_986;
    end else if (((tmp_fu_309_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        j4_reg_204 <= 31'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_fu_309_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        j_1_reg_238 <= 9'd0;
    end else if (((tmp_106_reg_1086 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        j_1_reg_238 <= j_3_reg_1110;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state42)) begin
        j_2_reg_261 <= 9'd0;
    end else if (((tmp_110_reg_1145 == 1'd0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        j_2_reg_261 <= j_5_reg_1184;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_46_fu_499_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        k_reg_216 <= 32'd0;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        k_reg_216 <= k_1_reg_1026;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_46_fu_499_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
                m_reg_181[31 : 1] <= m_1_fu_514_p2[31 : 1];
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                m_reg_181[1] <= 1'b1;
        m_reg_181[2] <= 1'b0;
        m_reg_181[3] <= 1'b0;
        m_reg_181[4] <= 1'b0;
        m_reg_181[5] <= 1'b0;
        m_reg_181[6] <= 1'b0;
        m_reg_181[7] <= 1'b0;
        m_reg_181[8] <= 1'b0;
        m_reg_181[9] <= 1'b0;
        m_reg_181[10] <= 1'b0;
        m_reg_181[11] <= 1'b0;
        m_reg_181[12] <= 1'b0;
        m_reg_181[13] <= 1'b0;
        m_reg_181[14] <= 1'b0;
        m_reg_181[15] <= 1'b0;
        m_reg_181[16] <= 1'b0;
        m_reg_181[17] <= 1'b0;
        m_reg_181[18] <= 1'b0;
        m_reg_181[19] <= 1'b0;
        m_reg_181[20] <= 1'b0;
        m_reg_181[21] <= 1'b0;
        m_reg_181[22] <= 1'b0;
        m_reg_181[23] <= 1'b0;
        m_reg_181[24] <= 1'b0;
        m_reg_181[25] <= 1'b0;
        m_reg_181[26] <= 1'b0;
        m_reg_181[27] <= 1'b0;
        m_reg_181[28] <= 1'b0;
        m_reg_181[29] <= 1'b0;
        m_reg_181[30] <= 1'b0;
        m_reg_181[31] <= 1'b0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state42)) begin
        omega2_reg_273 <= 15'd3383;
    end else if (((tmp_110_reg_1145 == 1'd0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        omega2_reg_273 <= grp_mod_r_fu_289_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state25)) begin
        omega4_reg_193 <= grp_mod_r_fu_284_ap_return;
    end else if (((tmp_fu_309_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        omega4_reg_193 <= 15'd1;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_fu_309_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        omega_1_reg_227 <= 15'd1;
    end else if (((tmp_106_reg_1086 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        omega_1_reg_227 <= grp_mod_r_fu_284_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state42)) begin
        omega_2_reg_250 <= 15'd1;
    end else if (((tmp_110_reg_1145 == 1'd0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        omega_2_reg_250 <= grp_mod_r_fu_284_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_46_fu_499_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        primrt_reg_170 <= primrt_1_reg_966;
    end else if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        primrt_reg_170 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_fu_530_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        a_addr_10_reg_1016[7 : 1] <= tmp_69_fu_589_p1[7 : 1];
        a_addr_11_reg_1021[7 : 1] <= tmp_72_fu_594_p1[7 : 1];
        a_addr_8_reg_1006[7 : 1] <= tmp_62_fu_560_p1[7 : 1];
        a_addr_9_reg_1011[7 : 1] <= tmp_65_fu_565_p1[7 : 1];
        k_1_reg_1026 <= k_1_fu_599_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_106_fu_706_p3 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        a_addr_5_reg_1095[7 : 1] <= tmp_49_fu_733_p1[7 : 1];
        a_addr_reg_1090 <= tmp_48_fu_722_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_110_fu_805_p3 == 1'd0) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        a_addr_6_reg_1154 <= tmp_82_fu_825_p1;
        tmp_112_reg_1149 <= tmp_112_fu_817_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_110_reg_1145 == 1'd0) & (1'b0 == ap_block_pp2_stage1_11001) & (1'b1 == ap_CS_fsm_pp2_stage1))) begin
        a_addr_7_reg_1174[7 : 1] <= tmp_88_fu_850_p1[7 : 1];
        tmp_84_reg_1169 <= tmp_84_fu_938_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        a_load_8_reg_1041 <= a_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001))) begin
        ap_reg_pp1_iter1_a_addr_5_reg_1095[7 : 1] <= a_addr_5_reg_1095[7 : 1];
        ap_reg_pp1_iter1_a_addr_reg_1090 <= a_addr_reg_1090;
        ap_reg_pp1_iter1_tmp_106_reg_1086 <= tmp_106_reg_1086;
        ap_reg_pp1_iter2_a_addr_5_reg_1095[7 : 1] <= ap_reg_pp1_iter1_a_addr_5_reg_1095[7 : 1];
        ap_reg_pp1_iter2_a_addr_reg_1090 <= ap_reg_pp1_iter1_a_addr_reg_1090;
        ap_reg_pp1_iter2_tmp_106_reg_1086 <= ap_reg_pp1_iter1_tmp_106_reg_1086;
        ap_reg_pp1_iter3_a_addr_5_reg_1095[7 : 1] <= ap_reg_pp1_iter2_a_addr_5_reg_1095[7 : 1];
        ap_reg_pp1_iter3_a_addr_reg_1090 <= ap_reg_pp1_iter2_a_addr_reg_1090;
        ap_reg_pp1_iter3_tmp_106_reg_1086 <= ap_reg_pp1_iter2_tmp_106_reg_1086;
        omega_1_cast3_reg_1081 <= omega_1_cast3_fu_702_p1;
        tmp_106_reg_1086 <= ap_phi_mux_j_1_phi_fu_242_p4[32'd8];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001))) begin
        ap_reg_pp2_iter1_a_addr_6_reg_1154 <= a_addr_6_reg_1154;
        ap_reg_pp2_iter1_tmp_110_reg_1145 <= tmp_110_reg_1145;
        ap_reg_pp2_iter2_a_addr_6_reg_1154 <= ap_reg_pp2_iter1_a_addr_6_reg_1154;
        ap_reg_pp2_iter2_tmp_110_reg_1145 <= ap_reg_pp2_iter1_tmp_110_reg_1145;
        ap_reg_pp2_iter3_a_addr_6_reg_1154 <= ap_reg_pp2_iter2_a_addr_6_reg_1154;
        ap_reg_pp2_iter3_tmp_110_reg_1145 <= ap_reg_pp2_iter2_tmp_110_reg_1145;
        omega2_cast1_reg_1140 <= omega2_cast1_fu_801_p1;
        omega_2_cast2_reg_1135 <= omega_2_cast2_fu_797_p1;
        tmp_110_reg_1145 <= ap_phi_mux_j_2_phi_fu_265_p4[32'd8];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp2_stage1_11001) & (1'b1 == ap_CS_fsm_pp2_stage1))) begin
        ap_reg_pp2_iter1_a_addr_7_reg_1174[7 : 1] <= a_addr_7_reg_1174[7 : 1];
        ap_reg_pp2_iter2_a_addr_7_reg_1174[7 : 1] <= ap_reg_pp2_iter1_a_addr_7_reg_1174[7 : 1];
        ap_reg_pp2_iter3_a_addr_7_reg_1174[7 : 1] <= ap_reg_pp2_iter2_a_addr_7_reg_1174[7 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_106_reg_1086 == 1'd0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage3) & (1'b0 == ap_block_pp1_stage3_11001))) begin
        j_3_reg_1110 <= j_3_fu_749_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_110_reg_1145 == 1'd0) & (1'b0 == ap_block_pp2_stage3_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage3))) begin
        j_5_reg_1184 <= j_5_fu_862_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        j_6_reg_986 <= j_6_fu_504_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_46_fu_499_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        omega4_cast_reg_991[15 : 0] <= omega4_cast_fu_510_p1[15 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state20)) begin
        omega_3_reg_1076 <= omega_3_fu_698_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_fu_309_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        primrt_1_reg_966 <= primrt_1_fu_423_p3;
        tmp_105_reg_977 <= tmp_105_fu_487_p1;
        tmp_45_reg_972 <= tmp_45_fu_479_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) | ((ap_reg_pp1_iter1_tmp_106_reg_1086 == 1'd0) & (1'b0 == ap_block_pp1_stage2_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage2)))) begin
        reg_294 <= a_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | (1'b1 == ap_CS_fsm_state15) | (1'b1 == ap_CS_fsm_state11) | (1'b1 == ap_CS_fsm_state10) | ((tmp_106_reg_1086 == 1'd0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)) | ((tmp_110_reg_1145 == 1'd0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001)))) begin
        reg_298 <= grp_mod_r_fu_284_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state25) | ((ap_reg_pp1_iter1_tmp_106_reg_1086 == 1'd0) & (1'b0 == ap_block_pp1_stage2_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage2)) | ((ap_reg_pp2_iter3_tmp_110_reg_1145 == 1'd0) & (1'b0 == ap_block_pp2_stage1_11001) & (ap_enable_reg_pp2_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1)) | ((ap_reg_pp1_iter2_tmp_106_reg_1086 == 1'd0) & (ap_enable_reg_pp1_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage3) & (1'b0 == ap_block_pp1_stage3_11001)) | ((ap_reg_pp2_iter1_tmp_110_reg_1145 == 1'd0) & (1'b0 == ap_block_pp2_stage3_11001) & (1'b1 == ap_CS_fsm_pp2_stage3) & (ap_enable_reg_pp2_iter1 == 1'b1)) | ((ap_reg_pp2_iter1_tmp_110_reg_1145 == 1'd0) & (1'b0 == ap_block_pp2_stage2_11001) & (1'b1 == ap_CS_fsm_pp2_stage2) & (ap_enable_reg_pp2_iter1 == 1'b1)))) begin
        reg_304 <= grp_mod_r_fu_284_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        t1_1_reg_1031 <= t1_1_fu_901_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_106_reg_1086 == 1'd0) & (1'b0 == ap_block_pp1_stage1_11001) & (1'b1 == ap_CS_fsm_pp1_stage1))) begin
        t1_reg_1105 <= t1_fu_918_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        t2_reg_1036 <= t2_fu_906_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_reg_pp1_iter1_tmp_106_reg_1086 == 1'd0) & (1'b1 == ap_CS_fsm_pp1_stage3) & (1'b0 == ap_block_pp1_stage3_11001))) begin
        tmp_54_reg_1120 <= tmp_54_fu_778_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_reg_pp1_iter3_tmp_106_reg_1086 == 1'd0) & (1'b0 == ap_block_pp1_stage1_11001) & (ap_enable_reg_pp1_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1))) begin
        tmp_55_reg_1130 <= grp_mod_r_fu_284_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state11)) begin
        tmp_75_reg_1051 <= tmp_75_fu_636_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state12)) begin
        tmp_79_reg_1061 <= tmp_79_fu_664_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_reg_pp2_iter1_tmp_110_reg_1145 == 1'd0) & (1'b0 == ap_block_pp2_stage3_11001) & (1'b1 == ap_CS_fsm_pp2_stage3))) begin
        tmp_86_reg_1194 <= tmp_86_fu_950_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_110_reg_1145 == 1'd0) & (1'b0 == ap_block_pp2_stage2_11001) & (1'b1 == ap_CS_fsm_pp2_stage2))) begin
        tmp_90_reg_1179 <= tmp_90_fu_944_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_reg_pp2_iter2_tmp_110_reg_1145 == 1'd0) & (1'b0 == ap_block_pp2_stage1_11001) & (1'b1 == ap_CS_fsm_pp2_stage1))) begin
        tmp_92_reg_1204 <= tmp_92_fu_956_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_reg_pp2_iter3_tmp_110_reg_1145 == 1'd0) & (1'b0 == ap_block_pp2_stage2_11001) & (ap_enable_reg_pp2_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage2))) begin
        tmp_93_reg_1214 <= grp_mod_r_fu_289_ap_return;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage3) & (ap_enable_reg_pp2_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage3))) begin
        a_address0 = ap_reg_pp2_iter3_a_addr_7_reg_1174;
    end else if (((1'b0 == ap_block_pp2_stage2) & (ap_enable_reg_pp2_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage2))) begin
        a_address0 = ap_reg_pp2_iter3_a_addr_6_reg_1154;
    end else if (((1'b0 == ap_block_pp2_stage1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1))) begin
        a_address0 = tmp_88_fu_850_p1;
    end else if (((1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        a_address0 = tmp_82_fu_825_p1;
    end else if (((1'b0 == ap_block_pp1_stage3) & (ap_enable_reg_pp1_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage3))) begin
        a_address0 = ap_reg_pp1_iter3_a_addr_5_reg_1095;
    end else if (((1'b0 == ap_block_pp1_stage2) & (1'b1 == ap_CS_fsm_pp1_stage2) & (ap_enable_reg_pp1_iter3 == 1'b1))) begin
        a_address0 = ap_reg_pp1_iter3_a_addr_reg_1090;
    end else if (((1'b0 == ap_block_pp1_stage1) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1))) begin
        a_address0 = ap_reg_pp1_iter1_a_addr_reg_1090;
    end else if (((1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        a_address0 = tmp_49_fu_733_p1;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        a_address0 = a_addr_8_reg_1006;
    end else if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state18))) begin
        a_address0 = a_addr_11_reg_1021;
    end else if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state16))) begin
        a_address0 = a_addr_9_reg_1011;
    end else if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state5))) begin
        a_address0 = a_addr_10_reg_1016;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        a_address0 = tmp_62_fu_560_p1;
    end else begin
        a_address0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | ((1'b0 == ap_block_pp1_stage1_11001) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage1)) | ((1'b0 == ap_block_pp1_stage2_11001) & (1'b1 == ap_CS_fsm_pp1_stage2) & (ap_enable_reg_pp1_iter3 == 1'b1)) | ((1'b0 == ap_block_pp2_stage1_11001) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1)) | ((1'b0 == ap_block_pp2_stage3_11001) & (ap_enable_reg_pp2_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage3)) | ((1'b0 == ap_block_pp2_stage2_11001) & (ap_enable_reg_pp2_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage2)) | ((ap_enable_reg_pp1_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage3) & (1'b0 == ap_block_pp1_stage3_11001)) | ((ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001)) | ((ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0) & (1'b0 == ap_block_pp1_stage0_11001)))) begin
        a_ce0 = 1'b1;
    end else begin
        a_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp2_stage3) & (ap_enable_reg_pp2_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage3))) begin
        a_d0 = p_trunc27_ext_fu_897_p1;
    end else if (((1'b0 == ap_block_pp2_stage2) & (ap_enable_reg_pp2_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage2))) begin
        a_d0 = p_trunc26_ext_fu_892_p1;
    end else if (((1'b0 == ap_block_pp1_stage3) & (ap_enable_reg_pp1_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage3))) begin
        a_d0 = p_trunc25_ext_fu_793_p1;
    end else if (((1'b0 == ap_block_pp1_stage2) & (1'b1 == ap_CS_fsm_pp1_stage2) & (ap_enable_reg_pp1_iter3 == 1'b1))) begin
        a_d0 = p_trunc24_ext_fu_788_p1;
    end else if ((1'b1 == ap_CS_fsm_state19)) begin
        a_d0 = p_trunc23_ext_fu_693_p1;
    end else if ((1'b1 == ap_CS_fsm_state18)) begin
        a_d0 = p_trunc21_ext_fu_688_p1;
    end else if ((1'b1 == ap_CS_fsm_state17)) begin
        a_d0 = p_trunc22_ext_fu_683_p1;
    end else if ((1'b1 == ap_CS_fsm_state16)) begin
        a_d0 = p_trunc_ext_fu_678_p1;
    end else begin
        a_d0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state18) | (1'b1 == ap_CS_fsm_state17) | (1'b1 == ap_CS_fsm_state16) | ((ap_reg_pp1_iter3_tmp_106_reg_1086 == 1'd0) & (1'b0 == ap_block_pp1_stage2_11001) & (1'b1 == ap_CS_fsm_pp1_stage2) & (ap_enable_reg_pp1_iter3 == 1'b1)) | ((ap_reg_pp2_iter3_tmp_110_reg_1145 == 1'd0) & (1'b0 == ap_block_pp2_stage3_11001) & (ap_enable_reg_pp2_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage3)) | ((ap_reg_pp2_iter3_tmp_110_reg_1145 == 1'd0) & (1'b0 == ap_block_pp2_stage2_11001) & (ap_enable_reg_pp2_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage2)) | ((ap_reg_pp1_iter3_tmp_106_reg_1086 == 1'd0) & (ap_enable_reg_pp1_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage3) & (1'b0 == ap_block_pp1_stage3_11001)))) begin
        a_we0 = 1'b1;
    end else begin
        a_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((tmp_106_fu_706_p3 == 1'd1)) begin
        ap_condition_pp1_exit_iter0_state26 = 1'b1;
    end else begin
        ap_condition_pp1_exit_iter0_state26 = 1'b0;
    end
end

always @ (*) begin
    if ((tmp_110_fu_805_p3 == 1'd1)) begin
        ap_condition_pp2_exit_iter0_state43 = 1'b1;
    end else begin
        ap_condition_pp2_exit_iter0_state43 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state59) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp1_iter1 == 1'b0) & (ap_enable_reg_pp1_iter3 == 1'b0) & (ap_enable_reg_pp1_iter0 == 1'b0) & (ap_enable_reg_pp1_iter2 == 1'b0))) begin
        ap_idle_pp1 = 1'b1;
    end else begin
        ap_idle_pp1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp2_iter2 == 1'b0) & (ap_enable_reg_pp2_iter0 == 1'b0) & (ap_enable_reg_pp2_iter3 == 1'b0) & (ap_enable_reg_pp2_iter1 == 1'b0))) begin
        ap_idle_pp2 = 1'b1;
    end else begin
        ap_idle_pp2 = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_106_reg_1086 == 1'd0) & (1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        ap_phi_mux_j_1_phi_fu_242_p4 = j_3_reg_1110;
    end else begin
        ap_phi_mux_j_1_phi_fu_242_p4 = j_1_reg_238;
    end
end

always @ (*) begin
    if (((tmp_110_reg_1145 == 1'd0) & (1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        ap_phi_mux_j_2_phi_fu_265_p4 = j_5_reg_1184;
    end else begin
        ap_phi_mux_j_2_phi_fu_265_p4 = j_2_reg_261;
    end
end

always @ (*) begin
    if (((tmp_110_reg_1145 == 1'd0) & (1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        ap_phi_mux_omega2_phi_fu_277_p4 = grp_mod_r_fu_289_ap_return;
    end else begin
        ap_phi_mux_omega2_phi_fu_277_p4 = omega2_reg_273;
    end
end

always @ (*) begin
    if (((tmp_106_reg_1086 == 1'd0) & (1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        ap_phi_mux_omega_1_phi_fu_231_p4 = grp_mod_r_fu_284_ap_return;
    end else begin
        ap_phi_mux_omega_1_phi_fu_231_p4 = omega_1_reg_227;
    end
end

always @ (*) begin
    if (((tmp_110_reg_1145 == 1'd0) & (1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        ap_phi_mux_omega_2_phi_fu_254_p4 = grp_mod_r_fu_284_ap_return;
    end else begin
        ap_phi_mux_omega_2_phi_fu_254_p4 = omega_2_reg_250;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state59)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state59) | (1'b1 == ap_CS_fsm_state19) | (1'b1 == ap_CS_fsm_state42) | (1'b1 == ap_CS_fsm_state1) | (1'b1 == ap_CS_fsm_state20) | (1'b1 == ap_CS_fsm_state5) | (1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state3) | (1'b1 == ap_CS_fsm_state2) | ((1'b1 == ap_block_pp1_stage2_11001) & (1'b1 == ap_CS_fsm_pp1_stage2)) | ((1'b1 == ap_block_pp1_stage1_11001) & (1'b1 == ap_CS_fsm_pp1_stage1)) | ((1'b1 == ap_block_pp2_stage1_11001) & (1'b1 == ap_CS_fsm_pp2_stage1)) | ((1'b1 == ap_block_pp2_stage3_11001) & (1'b1 == ap_CS_fsm_pp2_stage3)) | ((1'b1 == ap_block_pp2_stage2_11001) & (1'b1 == ap_CS_fsm_pp2_stage2)) | ((1'b1 == ap_block_pp1_stage3_11001) & (1'b1 == ap_CS_fsm_pp1_stage3)) | ((1'b1 == ap_block_pp2_stage0_11001) & (1'b1 == ap_CS_fsm_pp2_stage0)) | ((1'b1 == ap_block_pp1_stage0_11001) & (1'b1 == ap_CS_fsm_pp1_stage0)))) begin
        grp_mod_r_fu_284_ap_ce = 1'b0;
    end else begin
        grp_mod_r_fu_284_ap_ce = 1'b1;
    end
end

always @ (*) begin
    if (((ap_reg_pp2_iter2_tmp_110_reg_1145 == 1'd0) & (1'b0 == ap_block_pp2_stage1) & (ap_enable_reg_pp2_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage1))) begin
        grp_mod_r_fu_284_x = tmp_88_cast_fu_876_p1;
    end else if (((tmp_110_reg_1145 == 1'd0) & (1'b0 == ap_block_pp2_stage3) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage3))) begin
        grp_mod_r_fu_284_x = tmp_90_reg_1179;
    end else if (((tmp_110_reg_1145 == 1'd0) & (1'b0 == ap_block_pp2_stage2) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage2))) begin
        grp_mod_r_fu_284_x = tmp_84_reg_1169;
    end else if (((tmp_110_fu_805_p3 == 1'd0) & (1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        grp_mod_r_fu_284_x = omega_4_cast_fu_830_p1;
    end else if (((ap_reg_pp1_iter2_tmp_106_reg_1086 == 1'd0) & (1'b0 == ap_block_pp1_stage1) & (1'b1 == ap_CS_fsm_pp1_stage1) & (ap_enable_reg_pp1_iter2 == 1'b1))) begin
        grp_mod_r_fu_284_x = tmp_78_cast_fu_784_p1;
    end else if (((ap_reg_pp1_iter1_tmp_106_reg_1086 == 1'd0) & (1'b0 == ap_block_pp1_stage3) & (ap_enable_reg_pp1_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage3))) begin
        grp_mod_r_fu_284_x = tmp_76_cast_fu_773_p1;
    end else if (((tmp_106_reg_1086 == 1'd0) & (1'b0 == ap_block_pp1_stage2) & (1'b1 == ap_CS_fsm_pp1_stage2) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
        grp_mod_r_fu_284_x = t1_reg_1105;
    end else if (((tmp_106_fu_706_p3 == 1'd0) & (1'b0 == ap_block_pp1_stage0) & (ap_enable_reg_pp1_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage0))) begin
        grp_mod_r_fu_284_x = omega_cast_fu_738_p1;
    end else if ((1'b1 == ap_CS_fsm_state21)) begin
        grp_mod_r_fu_284_x = omega_3_reg_1076;
    end else if ((1'b1 == ap_CS_fsm_state14)) begin
        grp_mod_r_fu_284_x = tmp_122_cast_fu_674_p1;
    end else if ((1'b1 == ap_CS_fsm_state13)) begin
        grp_mod_r_fu_284_x = tmp_118_cast_fu_670_p1;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        grp_mod_r_fu_284_x = tmp_120_cast_fu_659_p1;
    end else if ((1'b1 == ap_CS_fsm_state11)) begin
        grp_mod_r_fu_284_x = tmp_116_cast_fu_631_p1;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        grp_mod_r_fu_284_x = t2_reg_1036;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        grp_mod_r_fu_284_x = t1_1_reg_1031;
    end else begin
        grp_mod_r_fu_284_x = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp2_stage1_11001) & (1'b1 == ap_CS_fsm_pp2_stage1)) | ((1'b0 == ap_block_pp2_stage3_11001) & (1'b1 == ap_CS_fsm_pp2_stage3)) | ((1'b0 == ap_block_pp2_stage2_11001) & (1'b1 == ap_CS_fsm_pp2_stage2)) | ((1'b1 == ap_CS_fsm_pp2_stage0) & (1'b0 == ap_block_pp2_stage0_11001)))) begin
        grp_mod_r_fu_289_ap_ce = 1'b1;
    end else begin
        grp_mod_r_fu_289_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if (((ap_reg_pp2_iter2_tmp_110_reg_1145 == 1'd0) & (1'b0 == ap_block_pp2_stage2) & (ap_enable_reg_pp2_iter2 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage2))) begin
        grp_mod_r_fu_289_x = tmp_95_cast_fu_888_p1;
    end else if (((tmp_110_fu_805_p3 == 1'd0) & (1'b0 == ap_block_pp2_stage0) & (ap_enable_reg_pp2_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage0))) begin
        grp_mod_r_fu_289_x = omega2_1_cast_fu_834_p1;
    end else begin
        grp_mod_r_fu_289_x = 'bx;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((tmp_fu_309_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((tmp_46_fu_499_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((icmp_fu_530_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state20;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            ap_NS_fsm = ap_ST_fsm_state12;
        end
        ap_ST_fsm_state12 : begin
            ap_NS_fsm = ap_ST_fsm_state13;
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            ap_NS_fsm = ap_ST_fsm_state15;
        end
        ap_ST_fsm_state15 : begin
            ap_NS_fsm = ap_ST_fsm_state16;
        end
        ap_ST_fsm_state16 : begin
            ap_NS_fsm = ap_ST_fsm_state17;
        end
        ap_ST_fsm_state17 : begin
            ap_NS_fsm = ap_ST_fsm_state18;
        end
        ap_ST_fsm_state18 : begin
            ap_NS_fsm = ap_ST_fsm_state19;
        end
        ap_ST_fsm_state19 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state20 : begin
            ap_NS_fsm = ap_ST_fsm_state21;
        end
        ap_ST_fsm_state21 : begin
            ap_NS_fsm = ap_ST_fsm_state22;
        end
        ap_ST_fsm_state22 : begin
            ap_NS_fsm = ap_ST_fsm_state23;
        end
        ap_ST_fsm_state23 : begin
            ap_NS_fsm = ap_ST_fsm_state24;
        end
        ap_ST_fsm_state24 : begin
            ap_NS_fsm = ap_ST_fsm_state25;
        end
        ap_ST_fsm_state25 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_pp1_stage0 : begin
            if ((~((ap_enable_reg_pp1_iter1 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone) & (tmp_106_fu_706_p3 == 1'd1) & (ap_enable_reg_pp1_iter0 == 1'b1)) & (1'b0 == ap_block_pp1_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage1;
            end else if (((ap_enable_reg_pp1_iter1 == 1'b0) & (1'b0 == ap_block_pp1_stage0_subdone) & (tmp_106_fu_706_p3 == 1'd1) & (ap_enable_reg_pp1_iter0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state42;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end
        end
        ap_ST_fsm_pp1_stage1 : begin
            if ((1'b0 == ap_block_pp1_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage1;
            end
        end
        ap_ST_fsm_pp1_stage2 : begin
            if ((1'b0 == ap_block_pp1_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage2;
            end
        end
        ap_ST_fsm_pp1_stage3 : begin
            if ((~((1'b0 == ap_block_pp1_stage3_subdone) & (ap_enable_reg_pp1_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage3) & (ap_enable_reg_pp1_iter2 == 1'b0)) & (1'b0 == ap_block_pp1_stage3_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage0;
            end else if (((1'b0 == ap_block_pp1_stage3_subdone) & (ap_enable_reg_pp1_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp1_stage3) & (ap_enable_reg_pp1_iter2 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state42;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp1_stage3;
            end
        end
        ap_ST_fsm_state42 : begin
            ap_NS_fsm = ap_ST_fsm_pp2_stage0;
        end
        ap_ST_fsm_pp2_stage0 : begin
            if ((~((1'b0 == ap_block_pp2_stage0_subdone) & (tmp_110_fu_805_p3 == 1'd1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (ap_enable_reg_pp2_iter1 == 1'b0)) & (1'b0 == ap_block_pp2_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage1;
            end else if (((1'b0 == ap_block_pp2_stage0_subdone) & (tmp_110_fu_805_p3 == 1'd1) & (ap_enable_reg_pp2_iter0 == 1'b1) & (ap_enable_reg_pp2_iter1 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_state59;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end
        end
        ap_ST_fsm_pp2_stage1 : begin
            if ((1'b0 == ap_block_pp2_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage1;
            end
        end
        ap_ST_fsm_pp2_stage2 : begin
            if ((1'b0 == ap_block_pp2_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage2;
            end
        end
        ap_ST_fsm_pp2_stage3 : begin
            if ((~((ap_enable_reg_pp2_iter2 == 1'b0) & (1'b0 == ap_block_pp2_stage3_subdone) & (ap_enable_reg_pp2_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage3)) & (1'b0 == ap_block_pp2_stage3_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage0;
            end else if (((ap_enable_reg_pp2_iter2 == 1'b0) & (1'b0 == ap_block_pp2_stage3_subdone) & (ap_enable_reg_pp2_iter3 == 1'b1) & (1'b1 == ap_CS_fsm_pp2_stage3))) begin
                ap_NS_fsm = ap_ST_fsm_state59;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp2_stage3;
            end
        end
        ap_ST_fsm_state59 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp1_stage0 = ap_CS_fsm[32'd25];

assign ap_CS_fsm_pp1_stage1 = ap_CS_fsm[32'd26];

assign ap_CS_fsm_pp1_stage2 = ap_CS_fsm[32'd27];

assign ap_CS_fsm_pp1_stage3 = ap_CS_fsm[32'd28];

assign ap_CS_fsm_pp2_stage0 = ap_CS_fsm[32'd30];

assign ap_CS_fsm_pp2_stage1 = ap_CS_fsm[32'd31];

assign ap_CS_fsm_pp2_stage2 = ap_CS_fsm[32'd32];

assign ap_CS_fsm_pp2_stage3 = ap_CS_fsm[32'd33];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state15 = ap_CS_fsm[32'd14];

assign ap_CS_fsm_state16 = ap_CS_fsm[32'd15];

assign ap_CS_fsm_state17 = ap_CS_fsm[32'd16];

assign ap_CS_fsm_state18 = ap_CS_fsm[32'd17];

assign ap_CS_fsm_state19 = ap_CS_fsm[32'd18];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state20 = ap_CS_fsm[32'd19];

assign ap_CS_fsm_state21 = ap_CS_fsm[32'd20];

assign ap_CS_fsm_state25 = ap_CS_fsm[32'd24];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state42 = ap_CS_fsm[32'd29];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state59 = ap_CS_fsm[32'd34];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_block_pp1_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp1_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp2_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_state26_pp1_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp1_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp1_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp1_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state30_pp1_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state31_pp1_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state32_pp1_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state33_pp1_stage3_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state34_pp1_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state35_pp1_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state36_pp1_stage2_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state37_pp1_stage3_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state38_pp1_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state39_pp1_stage1_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state40_pp1_stage2_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state41_pp1_stage3_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state43_pp2_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state44_pp2_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state45_pp2_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state46_pp2_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state47_pp2_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state48_pp2_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state49_pp2_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state50_pp2_stage3_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state51_pp2_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state52_pp2_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state53_pp2_stage2_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state54_pp2_stage3_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state55_pp2_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state56_pp2_stage1_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state57_pp2_stage2_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state58_pp2_stage3_iter3 = ~(1'b1 == 1'b1);

assign ap_enable_pp1 = (ap_idle_pp1 ^ 1'b1);

assign ap_enable_pp2 = (ap_idle_pp2 ^ 1'b1);

assign icmp_fu_530_p2 = (($signed(tmp_109_fu_520_p4) < $signed(25'd1)) ? 1'b1 : 1'b0);

assign j4_cast_fu_495_p1 = j4_reg_204;

assign j_3_fu_749_p2 = (9'd2 + j_1_reg_238);

assign j_4_fu_845_p2 = (tmp_112_reg_1149 | 8'd1);

assign j_5_fu_862_p2 = (9'd2 + j_2_reg_261);

assign j_6_fu_504_p2 = (j4_reg_204 + 31'd1);

assign j_fu_727_p2 = (tmp_108_fu_718_p1 | 8'd1);

assign k_1_fu_599_p2 = (m_reg_181 + k_reg_216);

assign m_1_fu_514_p2 = m_reg_181 << 32'd1;

assign omega2_1_cast_fu_834_p1 = omega2_1_fu_931_p2;

assign omega2_1_fu_931_p0 = 29'd2481;

assign omega2_1_fu_931_p1 = omega2_1_fu_931_p10;

assign omega2_1_fu_931_p10 = $unsigned(omega2_cast1_fu_801_p1);

assign omega2_cast1_fu_801_p1 = $signed(ap_phi_mux_omega2_phi_fu_277_p4);

assign omega4_cast4_fu_491_p1 = $signed(omega4_reg_193);

assign omega4_cast_fu_510_p1 = $unsigned(omega4_cast4_fu_491_p1);

assign omega_1_cast3_fu_702_p1 = $signed(ap_phi_mux_omega_1_phi_fu_231_p4);

assign omega_2_cast2_fu_797_p1 = $signed(ap_phi_mux_omega_2_phi_fu_254_p4);

assign omega_3_fu_698_p1 = omega4_cast_reg_991;

assign omega_3_fu_698_p2 = ($signed(primrt_1_reg_966) * $signed({{1'b0}, {omega_3_fu_698_p1}}));

assign omega_4_cast_fu_830_p1 = omega_4_fu_924_p2;

assign omega_4_fu_924_p0 = 29'd2481;

assign omega_4_fu_924_p1 = omega_4_fu_924_p10;

assign omega_4_fu_924_p10 = $unsigned(omega_2_cast2_fu_797_p1);

assign omega_cast_fu_738_p1 = omega_fu_911_p2;

assign omega_fu_911_p0 = 29'd2880;

assign omega_fu_911_p1 = omega_fu_911_p10;

assign omega_fu_911_p10 = $unsigned(omega_1_cast3_fu_702_p1);

assign p_lshr_f_fu_465_p4 = {{m_reg_181[31:1]}};

assign p_lshr_fu_445_p4 = {{p_neg_fu_439_p2[31:1]}};

assign p_neg_fu_439_p2 = (32'd0 - m_reg_181);

assign p_neg_t_fu_459_p2 = (32'd0 - tmp_41_fu_455_p1);

assign p_trunc21_ext_fu_688_p1 = $signed(reg_298);

assign p_trunc22_ext_fu_683_p1 = $signed(reg_298);

assign p_trunc23_ext_fu_693_p1 = $signed(reg_298);

assign p_trunc24_ext_fu_788_p1 = $signed(reg_304);

assign p_trunc25_ext_fu_793_p1 = $signed(tmp_55_reg_1130);

assign p_trunc26_ext_fu_892_p1 = $signed(reg_304);

assign p_trunc27_ext_fu_897_p1 = $signed(tmp_93_reg_1214);

assign p_trunc_ext_fu_678_p1 = $signed(reg_298);

assign primrt_1_fu_423_p3 = ((tmp_29_fu_417_p2[0:0] === 1'b1) ? sel_tmp11_cast_fu_409_p3 : sel_tmp9_fu_389_p3);

assign sel_tmp11_cast_fu_409_p3 = ((sel_tmp7_fu_403_p2[0:0] === 1'b1) ? 32'd7680 : 32'd3383);

assign sel_tmp1_fu_321_p3 = ((sel_tmp_fu_315_p2[0:0] === 1'b1) ? 32'd6601 : primrt_reg_170);

assign sel_tmp2_fu_329_p2 = ((m_reg_181 == 32'd64) ? 1'b1 : 1'b0);

assign sel_tmp3_cast_fu_341_p3 = ((sel_tmp4_fu_335_p2[0:0] === 1'b1) ? 32'd7584 : 32'd6569);

assign sel_tmp3_fu_397_p2 = ((m_reg_181 == 32'd4) ? 1'b1 : 1'b0);

assign sel_tmp4_fu_335_p2 = ((m_reg_181 == 32'd32) ? 1'b1 : 1'b0);

assign sel_tmp5_fu_355_p3 = ((tmp_27_fu_349_p2[0:0] === 1'b1) ? sel_tmp3_cast_fu_341_p3 : sel_tmp1_fu_321_p3);

assign sel_tmp6_fu_363_p2 = ((m_reg_181 == 32'd16) ? 1'b1 : 1'b0);

assign sel_tmp7_cast_fu_375_p3 = ((sel_tmp8_fu_369_p2[0:0] === 1'b1) ? 32'd5756 : 32'd1728);

assign sel_tmp7_fu_403_p2 = ((m_reg_181 == 32'd2) ? 1'b1 : 1'b0);

assign sel_tmp8_fu_369_p2 = ((m_reg_181 == 32'd8) ? 1'b1 : 1'b0);

assign sel_tmp9_fu_389_p3 = ((tmp_28_fu_383_p2[0:0] === 1'b1) ? sel_tmp7_cast_fu_375_p3 : sel_tmp5_fu_355_p3);

assign sel_tmp_fu_315_p2 = ((m_reg_181 == 32'd128) ? 1'b1 : 1'b0);

assign t1_1_cast_fu_763_p1 = $unsigned(t1_1_trunc_ext_fu_759_p1);

assign t1_1_fu_901_p0 = omega4_cast_reg_991;

assign t1_1_fu_901_p1 = t1_1_fu_901_p10;

assign t1_1_fu_901_p10 = a_q0;

assign t1_1_trunc_ext_fu_759_p1 = $signed(reg_304);

assign t1_3_cast_fu_617_p1 = $unsigned(t1_3_trunc_ext_fu_613_p1);

assign t1_3_trunc_ext_fu_613_p1 = $signed(reg_298);

assign t1_fu_918_p0 = t1_fu_918_p00;

assign t1_fu_918_p00 = a_q0;

assign t1_fu_918_p1 = t1_fu_918_p10;

assign t1_fu_918_p10 = $unsigned(omega_1_cast3_reg_1081);

assign t2_1_cast_fu_646_p1 = $unsigned(t2_1_trunc_ext_fu_642_p1);

assign t2_1_trunc_ext_fu_642_p1 = $signed(reg_298);

assign t2_fu_906_p0 = omega4_cast_reg_991;

assign t2_fu_906_p1 = t2_fu_906_p10;

assign t2_fu_906_p10 = a_q0;

assign tmp_104_fu_431_p3 = m_reg_181[32'd31];

assign tmp_105_fu_487_p1 = tmp_45_fu_479_p3[30:0];

assign tmp_106_fu_706_p3 = ap_phi_mux_j_1_phi_fu_242_p4[32'd8];

assign tmp_108_fu_718_p1 = ap_phi_mux_j_1_phi_fu_242_p4[7:0];

assign tmp_109_fu_520_p4 = {{k_reg_216[31:7]}};

assign tmp_110_fu_805_p3 = ap_phi_mux_j_2_phi_fu_265_p4[32'd8];

assign tmp_111_fu_536_p1 = k_reg_216[30:0];

assign tmp_112_fu_817_p1 = ap_phi_mux_j_2_phi_fu_265_p4[7:0];

assign tmp_116_cast_fu_631_p1 = tmp_73_fu_625_p2;

assign tmp_118_cast_fu_670_p1 = $signed(tmp_75_reg_1051);

assign tmp_120_cast_fu_659_p1 = tmp_77_fu_653_p2;

assign tmp_122_cast_fu_674_p1 = $signed(tmp_79_reg_1061);

assign tmp_27_fu_349_p2 = (sel_tmp4_fu_335_p2 | sel_tmp2_fu_329_p2);

assign tmp_28_fu_383_p2 = (sel_tmp8_fu_369_p2 | sel_tmp6_fu_363_p2);

assign tmp_29_fu_417_p2 = (sel_tmp7_fu_403_p2 | sel_tmp3_fu_397_p2);

assign tmp_41_fu_455_p1 = p_lshr_fu_445_p4;

assign tmp_42_fu_475_p1 = p_lshr_f_fu_465_p4;

assign tmp_45_fu_479_p3 = ((tmp_104_fu_431_p3[0:0] === 1'b1) ? p_neg_t_fu_459_p2 : tmp_42_fu_475_p1);

assign tmp_46_fu_499_p2 = (($signed(j4_cast_fu_495_p1) < $signed(tmp_45_reg_972)) ? 1'b1 : 1'b0);

assign tmp_48_fu_722_p1 = ap_phi_mux_j_1_phi_fu_242_p4;

assign tmp_49_fu_733_p1 = j_fu_727_p2;

assign tmp_52_fu_767_p2 = (t1_1_cast_fu_763_p1 + u1_cast_fu_755_p1);

assign tmp_54_fu_778_p2 = (u1_cast_fu_755_p1 - t1_1_cast_fu_763_p1);

assign tmp_58_fu_540_p2 = (j4_reg_204 + tmp_111_fu_536_p1);

assign tmp_59_fu_546_p3 = {{tmp_58_fu_540_p2}, {1'd0}};

assign tmp_60_fu_554_p2 = (tmp_59_fu_546_p3 | 32'd1);

assign tmp_62_fu_560_p1 = $signed(tmp_60_fu_554_p2);

assign tmp_65_fu_565_p1 = $signed(tmp_59_fu_546_p3);

assign tmp_66_fu_570_p2 = (tmp_105_reg_977 + tmp_58_fu_540_p2);

assign tmp_67_fu_575_p3 = {{tmp_66_fu_570_p2}, {1'd0}};

assign tmp_68_fu_583_p2 = (tmp_67_fu_575_p3 | 32'd1);

assign tmp_69_fu_589_p1 = $signed(tmp_68_fu_583_p2);

assign tmp_72_fu_594_p1 = $signed(tmp_67_fu_575_p3);

assign tmp_73_fu_625_p2 = (u1_1_cast_fu_621_p1 + t1_3_cast_fu_617_p1);

assign tmp_75_fu_636_p2 = (u1_1_cast_fu_621_p1 - t1_3_cast_fu_617_p1);

assign tmp_76_cast_fu_773_p1 = tmp_52_fu_767_p2;

assign tmp_77_fu_653_p2 = (u2_cast_fu_650_p1 + t2_1_cast_fu_646_p1);

assign tmp_78_cast_fu_784_p1 = $signed(tmp_54_reg_1120);

assign tmp_79_fu_664_p2 = (u2_cast_fu_650_p1 - t2_1_cast_fu_646_p1);

assign tmp_82_fu_825_p1 = ap_phi_mux_j_2_phi_fu_265_p4;

assign tmp_84_fu_938_p0 = tmp_84_fu_938_p00;

assign tmp_84_fu_938_p00 = a_q0;

assign tmp_84_fu_938_p1 = tmp_84_fu_938_p10;

assign tmp_84_fu_938_p10 = $unsigned(omega_2_cast2_reg_1135);

assign tmp_86_fu_950_p0 = 30'd7651;

assign tmp_86_fu_950_p1 = tmp_86_fu_950_p10;

assign tmp_86_fu_950_p10 = $unsigned(tmp_87_trunc_ext_fu_868_p1);

assign tmp_87_trunc_ext_fu_868_p1 = $signed(reg_304);

assign tmp_88_cast_fu_876_p1 = tmp_86_reg_1194;

assign tmp_88_fu_850_p1 = j_4_fu_845_p2;

assign tmp_90_fu_944_p0 = tmp_90_fu_944_p00;

assign tmp_90_fu_944_p00 = a_q0;

assign tmp_90_fu_944_p1 = tmp_90_fu_944_p10;

assign tmp_90_fu_944_p10 = $unsigned(omega2_cast1_reg_1140);

assign tmp_92_fu_956_p0 = 30'd7651;

assign tmp_92_fu_956_p1 = tmp_92_fu_956_p10;

assign tmp_92_fu_956_p10 = $unsigned(tmp_94_trunc_ext_fu_880_p1);

assign tmp_94_trunc_ext_fu_880_p1 = $signed(reg_304);

assign tmp_95_cast_fu_888_p1 = tmp_92_reg_1204;

assign tmp_fu_309_p2 = (($signed(m_reg_181) < $signed(32'd129)) ? 1'b1 : 1'b0);

assign u1_1_cast_fu_621_p1 = reg_294;

assign u1_cast_fu_755_p1 = reg_294;

assign u2_cast_fu_650_p1 = a_load_8_reg_1041;

always @ (posedge ap_clk) begin
    omega4_cast_reg_991[31:16] <= 16'b0000000000000000;
    a_addr_8_reg_1006[0] <= 1'b1;
    a_addr_9_reg_1011[0] <= 1'b0;
    a_addr_10_reg_1016[0] <= 1'b1;
    a_addr_11_reg_1021[0] <= 1'b0;
    a_addr_5_reg_1095[0] <= 1'b1;
    ap_reg_pp1_iter1_a_addr_5_reg_1095[0] <= 1'b1;
    ap_reg_pp1_iter2_a_addr_5_reg_1095[0] <= 1'b1;
    ap_reg_pp1_iter3_a_addr_5_reg_1095[0] <= 1'b1;
    a_addr_7_reg_1174[0] <= 1'b1;
    ap_reg_pp2_iter1_a_addr_7_reg_1174[0] <= 1'b1;
    ap_reg_pp2_iter2_a_addr_7_reg_1174[0] <= 1'b1;
    ap_reg_pp2_iter3_a_addr_7_reg_1174[0] <= 1'b1;
    m_reg_181[0] <= 1'b0;
end

endmodule //inv_ntt2
